checkpointing_table_id: "bigquery_to_datastore_via_beam.checkpointing"
name: "FakePii"
source_table_id: "bigquery_to_datastore_via_beam.fake_pii_data"
source_timestamp_column: "last_updated_timestamp"
source_table_columns:
  - "uuid"
  - "full_name"
  - "email"
  - "address"
  - "phone_number"
  - "birthdate"
  - "last_updated_timestamp"
datastore_key_column: "uuid"
datastore_namespace: "demo"
datastore_kind: "FakePiiDemo"